-- MySQL Script generated by MySQL Workbench
-- Wed Mar 22 15:03:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema register_form
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema register_form
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `register_form` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_mysql500_ci ;
USE `register_form` ;

-- -----------------------------------------------------
-- Table `register_form`.`register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `register_form`.`register` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `email` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NULL,
  `intr1` VARCHAR(45) NULL,
  `intr2` VARCHAR(45) NULL,
  `address` VARCHAR(100) NULL,
  `PROVINCE_ID` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
